# Generated by Django 5.2.5 on 2026-06-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manages_stock',
            field=models.BooleanField(default=True),
        ),
    ]
