# Generated by Django 5.2.5 on 2026-09-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='landing_image',
            field=models.ImageField(blank=True, null=True, upload_to='productos/landing/'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_image',
            field=models.ImageField(blank=True, null=True, upload_to='productos/materiales/'),
        ),
    ]
