# Generated by Django 5.2.5 on 2026-09-25 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_landing_image_product_material_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productos/catalogo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_images', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
