# Generated by Django 5.2.5 on 2026-09-25 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productcatalogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productos/materiales/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_images', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
